# Generated by Django 3.2.6 on 2021-11-16 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='greedy',
            fields=[
                ('country', models.CharField(max_length=250)),
                ('device', models.CharField(max_length=250)),
                ('requests', models.IntegerField()),
                ('spent', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requests', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.greedy')),
            ],
        ),
    ]
